version: "3.7"
services:
    predictd:
        image: predictd
        build: ./predictd
        tty: true
        networks:
            sysnet:
    sdrd:
        image: sdrd
        build: ./sdrd
        ports:
            - "6020:6020/udp"
        privileged: true
        networks:
            sysnet:
        depends_on:
            - icecast
    predictd-api:
        image: predictd-api
        build: ./predictd-api
        ports:
            - "1881:1880"
        networks:
            sysnet:
        depends_on:
            - predictd
    sdrd-api:
        image: sdrd-api
        build: ./sdrd-api
        ports:
            - "1882:1880"
        networks:
            - sysnet
        volumes:
            - ./sdrd-api:/data
        depends_on:
            - sdrd
    icecast:
        image: icecast
        build: ./icecast
        ports:
            - "8000:8000"
        environment:
            - ICECAST_SOURCE_PASSWORD=hackme
            - ICECAST_ADMIN_PASSWORD=hackme
            - ICECAST_RELAY_PASSWORD=relay
            - ICECAST_ADMIN_USERNAME=admin
            - ICECAST_ADMIN_EMAIL=ansofive@gmail.com
            - ICECAST_LOCATION=DM45ee
            - ICECAST_HOSTNAME=icecast
            - ICECAST_MAX_CLIENTS=50
            - ICECAST_MAX_SOURCES=50
        networks:
            sysnet:    
    stream-diag:
        image: stream-diag
        build: ./stream-diag
        networks:
            sysnet:
        depends_on:
            - icecast
    db:
        image: couchdb
        volumes:
            - type: volume
              source: dbdata
              target: /opt/couchdb/data
        ports:
            - "5984:5984"
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password 
        networks:
            sysnet:    
networks:
    sysnet:
volumes:
    dbdata:
