version: "3.7"
services:
    predictd:
        image: predictd
        build: ./predictd
        ports:
            - "1210:1210/udp"
        tty: true
        networks:
            sysnet:
        restart: unless-stopped
    sdrd:
        image: sdrd
        build: ./sdrd
        ports:
            - "6020:6020/udp"
        privileged: true
        networks:
            sysnet:
        restart: unless-stopped
    api:
        image: api
        build: ./api
        ports:
            - "1880:1880"
        networks:
            sysnet:
        restart: unless-stopped
    stream:
        image: icecast
        build: ./icecast
        ports:
            - "8000:8000"
        environment:
            - ICECAST_SOURCE_PASSWORD=hackme
            - ICECAST_ADMIN_PASSWORD=hackme
            - ICECAST_RELAY_PASSWORD=relay
            - ICECAST_ADMIN_USERNAME=admin
            - ICECAST_ADMIN_EMAIL=ansofive@gmail.com
            - ICECAST_LOCATION=DM45ee
            - ICECAST_HOSTNAME=stream
            - ICECAST_MAX_CLIENTS=50
            - ICECAST_MAX_SOURCES=50
        networks:
            sysnet:
        restart: unless-stopped
    alpine-builder:
        image: alpine-builder
        build: 
            context: ./build
            dockerfile: alpine.Dockerfile
        command: ["true"]
    debian-builder:
        image: debian-builder
        build: 
            context: ./build
            dockerfile: debian.Dockerfile
        command: ["true"]
networks:
    sysnet:
