
version: "3.7"
services:
    predictd:
        image: predictd
        build: ./predictd
        tty: true
        networks:
            - default
    rtld:
        image: rtld
        build: ./rtld
        ports:
            - "9001:9001"
        privileged: true
        networks:
            - default
    predictd-api:
        image: predictd-api
        build: ./predictd-api
        ports:
            - "1881:1880"
        networks:
            - default
    rtld-api:
        image: rtld-api
        build: ./rtld-api
        ports:
            - "1882:1880"
        networks:
            - default
    peerd:
        image: peerjs/peerjs-server
        ports:
            - "9002:9000"
        networks:
            - default
